### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [LorenzoAlbornoz/Backend-Music-Store#10]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/LorenzoAlbornoz/Backend-Music-Store/assets/53904695/dd9c8cce-3d49-44fb-8425-345047168974)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by LorenzoAlbornoz** [comment]
Buenas Nicolas, ya esta resuelto
